eureka:
  client:
    serviceUrl:
      defaultZone: https://betting-app-discovery-server.herokuapp.com/eureka
spring:
  liquibase:
    change-log: classpath:db/changelog/main-changelog.xml
    enabled: true