eureka:
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVER}:${DISCOVERY_SERVER_PORT}/eureka
spring:
  liquibase:
    change-log: classpath:db/changelog/main-changelog.xml
    enabled: true