server:
  port: 7070
  servlet:
    context-path: /auth

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authorization-db
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5432/authorization-db
    username: '{cipher}b0b3690817b522c75fbea0feaa7fc6290ac070841f7d3a884f0c5217f372ae582a33c9438378c46a1054625dfdfeaa73'
    password: '{cipher}3e604c0341b5b3e28f5ea4c17ffcc6caba234652afe72cf6182210891e8982ab9afd14353e77fb1e364abda7ebf6f8b6'
    initialization-mode: always
    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true
      properties:
        hibernate:
          jdbc:
            lob:
              non_contextual_creation: true
      database-platform: org.hibernate.dialect.PostgreSQL9Dialect

oauth2:
  config:
    client-id: betting-app-v2-kasdlj
    client-secret: '{cipher}8e238892099bc284dbff541d94d5a32d80e513858c239ab0a2076e410985eae876e1519d1a419b05bbd1466b16c4f45fc1bb63ed719da004b8da9fe88abcedb3'
    redirect-uris: http://localhost:8080/login/oauth2/code/

token:
  accessTokenValiditySeconds: 3600
  refreshTokenValiditySeconds: 18000

encrypt:
  key: ${ENCRYPT_KEY}