server:
  port: 7070
  servlet:
    context-path: /auth

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authorization-db
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5432/authorization-db
    username: '{cipher}b0b3690817b522c75fbea0feaa7fc6290ac070841f7d3a884f0c5217f372ae582a33c9438378c46a1054625dfdfeaa73'
    password: '{cipher}3e604c0341b5b3e28f5ea4c17ffcc6caba234652afe72cf6182210891e8982ab9afd14353e77fb1e364abda7ebf6f8b6'
    initialization-mode: always
    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true
      properties:
        hibernate:
          jdbc:
            lob:
              non_contextual_creation: true
      database-platform: org.hibernate.dialect.PostgreSQL9Dialect

config:
  oauth2:
    loginUrl: http://localhost:8080/auth/login
    logoutSuccessUrl: http://localhost:8080/
    clientid: betting-app-v2-kasdlj
    clientSecret: fDw7Mpkk5czHNuSRtmhGmAGL42CaxQB9
    redirectUris: http://localhost:8080/login/oauth2/code/

token:
  accessTokenValiditySeconds: 3600
  refreshTokenValiditySeconds: 18000

encrypt:
  key: ${ENCRYPT_KEY}