server:
  port: 7070
  servlet:
    context-path: /auth

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authorization-db
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5432/authorization-db
    username: '{cipher}0ab93e039f5de72e1d9774b0f7b3e4699c15f4232e34aa07f6ce32df904f0fd17c9b837d5443342ee5595cecdca41faa'
    password: '{cipher}b2cbd09eda2eb9bd528d09c12d1b7dbba9a26a6bc7cff2d81c89fabaa9b1a1fd61276e858a593618b2901a4038399b60'
    initialization-mode: always
    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true
      properties:
        hibernate:
          jdbc:
            lob:
              non_contextual_creation: true
      database-platform: org.hibernate.dialect.PostgreSQL9Dialect

config:
  oauth2:
    loginUrl: http://localhost:8080/auth/login
    logoutSuccessUrl: http://localhost:8080/
    clientid: betting-app-v2-kasdlj
    clientSecret: fDw7Mpkk5czHNuSRtmhGmAGL42CaxQB9
    redirectUris: http://localhost:8080/login/oauth2/code/

token:
  accessTokenValiditySeconds: 3600
  refreshTokenValiditySeconds: 18000