server:
  port: ${AUTHORIZATION_SERVER_PORT}
  servlet:
    context-path: /auth

spring:
  datasource:
    url: jdbc:postgresql://${AUTHORIZATION_DB}:${AUTHORIZATION_DB_PORT}/authorization-db
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://${AUTHORIZATION_DB}:${AUTHORIZATION_DB_PORT}/authorization-db
    username: '{cipher}6117ccd79c38568da5f0f4734271bde31c4749061f388c257958a30bf47a5c220b70620d32c8cd73f0a4d63136ac33a3'
    password: '{cipher}ec09316224982eb8a35ec00c3ce2d8d6d48a90eb0c1895aa962bfc19c991753d6c4aceaf86aa4b383377fff723c23f04'
    initialization-mode: always
    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true
      properties:
        hibernate:
          jdbc:
            lob:
              non_contextual_creation: true
      database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  rabbitmq:
    host: ${RABBIT}
    port: ${RABBIT_PORT}
    username: '{cipher}0aa4e76bb5b4b56cabe6a25cab50cce2df86bb5edd646a48afd28e5d15382d6f'
    password: '{cipher}866afd400be760d41f0b56eeaeef01d978c9a2d8bf55896de9cdab43de97877c'
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: bettingapp71@gmail.com
    password: '{cipher}da8d09a63f69fab6fd44d42b9a63fd4a3c197ff9917e0977e781224cb2685a6b25028e949731918d0927b369a6d19e4d'
    properties:
      mail:
        smtp:
          starttls:
            enable: true

oauth2:
  config:
    client-id: betting-app-v2-kasdlj
    client-secret: '{cipher}8e238892099bc284dbff541d94d5a32d80e513858c239ab0a2076e410985eae876e1519d1a419b05bbd1466b16c4f45fc1bb63ed719da004b8da9fe88abcedb3'
    redirect-uris: http://localhost:8080/login
    signingKey: '{cipher}a23f9cd65d6c59b46b22b72973687892059b6fee924181fc5b75b7bf564c6b3a'

encrypt:
  key: ${ENCRYPT_KEY}

activation:
  url: http://localhost:8080/authorization-service/users/activation
