server:
  port: 8010

spring:
  datasource:
    url: jdbc:postgresql://user-database:5433/user-db
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://user-database:5433/user-db
    username: '{cipher}84da77612e53cde0822fef4e5ed4942d5f3c1571cc11d581c564b2a36c6e3672'
    password: '{cipher}3ee9af83d813b2a50a114438200337a19dbab14853ee96d6ce3b91f81f62699d'
    initialization-mode: always
    jpa:
      hibernate:
        ddl-auto: none
        naming:
          implicit-strategy: org.hibernate.boot.aggregate.naming.ImplicitNamingStrategyComponentPathImpl
          physical-strategy: org.hibernate.boot.aggregate.naming.PhysicalNamingStrategyStandardImpl
      show-sql: true
      properties:
        hibernate:
          jdbc:
            lob:
              non_contextual_creation: true
      database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  rabbitmq:
    username: '{cipher}a1ea071fe80e1f69c0935c781786d371cd88dd667fb774af41fcf6ccb84cb6bd'
    password: '{cipher}a1ea071fe80e1f69c0935c781786d371cd88dd667fb774af41fcf6ccb84cb6bd'

oauth2:
  config:
    signingKey: '{cipher}a23f9cd65d6c59b46b22b72973687892059b6fee924181fc5b75b7bf564c6b3a'

encrypt:
  key: ${ENCRYPT_KEY}

